Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@blajdo-pb-pg 
procter-gamble
/
pampers-BDU-data-quality
Private
Code
Issues
Pull requests
6
Actions
Projects
Wiki
Security
Insights
Settings
pampers-BDU-data-quality/.github/workflows/pr-bdu-dq-trigger-open.yml
@jdubowik
jdubowik action_rename
Latest commit 3672225 9 days ago
 History
 1 contributor
58 lines (47 sloc)  2.2 KB
   
name: pr-bdu-dq-trigger-open

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    types: [ opened ]
    paths: [ user/bdu/data_quality/** ]    

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

          
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pandas           
      
      - name: validate test definition files & create CR ticket    
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          mkdir -p releases
          FILES_COUNT=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER | jq -r '.changed_files')
          for p in $(seq $(expr $FILES_COUNT / 100 + 1))
          do
            URL="https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files?per_page=100&page=$p"
            echo "GET: $URL"
            FILES=$(curl -s -X GET -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $URL | jq -r '[.[] .filename] | join(",")')
            echo $FILES
          done
